export default [
    { id: 1, value: 'C',backgroundColor:'#a6a6a6' },
    { id: 2, value: '+/-',backgroundColor:'#a6a6a6' },
    { id: 3, value: '%',backgroundColor:'#a6a6a6' },
    { id: 4, value: '/',backgroundColor:'#f09a36' },
    { id: 5, value: '7' },
    { id: 6, value: '8' },
    { id: 7, value: '9' },
    { id: 8, value: 'x',backgroundColor:'#f09a36' },
    { id: 9, value: '4' },
    { id: 10, value: '5' },
    { id: 11, value: '6' },
    { id: 12, value: '-',backgroundColor:'#f09a36' },
    { id: 13, value: '1' },
    { id: 14, value: '2' },
    { id: 15, value: '3' },
    { id: 16, value: '+',backgroundColor:'#f09a36' },
    { id: 17, value: '0' },
    { id: 18, value: '.' },
    { id: 19, value: '=' },
]